version: 2
jobs:
  build:
    
    working_directory: ~/taskmanager

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:

      - checkout

      - restore_cache:
          key: taskmanager-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: taskmanager-{{ checksum "pom.xml" }}
      
      - run: mvn test
      
      - run: mvn clean install package -Pweb
      
      - run: mvn clean install -Pscheduler
      
  workflows:
  version: 2
  workflow:
    jobs:
    - build


  
