apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web
        image: XXXXXXXXXXXXX:5000/endpoint:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: db-service
      - name: scheduler
        image: XXXXXXXXX:5000/scheduler:latest
        env:
        - name: DBHOST
          value: db-service

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /endpoint
        backend:
          serviceName: web-service
          servicePort: 8080
