
version: 2
jobs:
  build:
    
    working_directory: ~/taskmanager

      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: taskmanager-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/mvn-spring-project-0.0.1-SNAPSHOT.jar
